//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SEGURO
    {
        public TIPO_SEGURO()
        {
            this.historia = new HashSet<historia>();
        }
    
        public int id_tipo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<historia> historia { get; set; }
    }
}
